sudo: required
services:
  - docker

before_install:
  - docker build -t oz4899/docker-react-test -f Dockerfile.dev .

script:
  - docker run oz4899/docker-react-test npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name:  elasticbeanstalk-ap-northeast-1-481678475449
  bucket: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"